### PR TITLE
Use setuptools declarative configuration

### PR DESCRIPTION
**Pull request by jdufresne**
https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

Avoids mixing logic and configuration. Now, all setup values can be
easily parsed by external tools.

### CODE REVIEW

**Comment by pwaller** [comment]
The tests failed in this one, presume #55 was meant to fix this one? Please can you rebase?

**Comment by jdufresne** [comment]
Rebased :slightly_smiling_face:

**Comment by pwaller** [comment]
Do you have a specific use case for these, and do you need this to be in a released version to be able to use it?

(And do you have any other changes you'd like to bundle up into a release?)

**Comment by jdufresne** [comment]
> Do you have a specific use case for these, and do you need this to be in a released version to be able to use it?

Nope. Please don't feel the need to cut a release until something more substantial comes along.

Every once in a while I scan projects I use for common patterns, such as using the old style `setup.py`. If it looks easy enough to fix, I go ahead. Just as a way to help out.

**Pull request merged**
