### PR TITLE
Add support for Python profiler module

### PR DESCRIPTION
**Pull request by danalsan**
Files produced by standard python profiler module are now supported

### CODE REVIEW

**Comment by pwaller** [comment]
Hi, Thanks for the pull request! Can you provide instructions on how I might use this? A minimal case would be very useful. Also, could you add your name to CONTRIBUTORS.txt and a changelog entry at the bottom of the README.txt. If you do these things and I test it and it works, I will merge and cut a new release fairly quickly after that (assuming I can get it to work).

**Comment by danalsan** [comment]
Hi Peter, Thanks to you :)

I had a profiler output from standard python profile module (actually from greenthread profile) and running the tool on it throws this error:

pyprof2calltree -i combined.prof -o combined.xx
Traceback (most recent call last):
  File "/usr/bin/pyprof2calltree", line 9, in <module>
    load_entry_point('pyprof2calltree==1.4.0', 'console_scripts', 'pyprof2calltree')()
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 324, in main
    kg = CalltreeConverter(pstats.Stats(options.infile))
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 160, in __init__
    self.entries = pstats2entries(profiling_data)
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 128, in pstats2entries
    cc, nc, tt, ct = call_info
TypeError: 'int' object is not iterable

The thing is that when you're doing the 2nd pass you expect that to be a tuple but for this kind of files, it's not and it only contains the callcount.

My patch handles that situation similarly as this other project [0] does.
Also, I have added your suggestions to my commit :) Thanks!

[0] https://github.com/jrfonseca/gprof2dot

**Comment by pwaller** [comment]
Thanks for that @danalsan. I've got my hands rather full at the moment. Can you give me exact steps to test this on an example which demonstrates that your patch works?

**Comment by danalsan** [comment]
@pwaller sure. Please, try this simple python file [0]

* Generate pstats file: 
   ` python -m profile -o simple.prof simple.py`
* Try to convert the file to calltree:
```
   $ pyprof2calltree -i simple.prof  -o simple.ct
Traceback (most recent call last):
  File "/usr/bin/pyprof2calltree", line 9, in <module>
    load_entry_point('pyprof2calltree==1.4.0', 'console_scripts', 'pyprof2calltree')()
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 324, in main
    kg = CalltreeConverter(pstats.Stats(options.infile))
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 160, in __init__
    self.entries = pstats2entries(profiling_data)
  File "/usr/lib/python2.7/site-packages/pyprof2calltree.py", line 128, in pstats2entries
    cc, nc, tt, ct = call_info
TypeError: 'int' object is not iterable
```
After applying my patch, you should see that it'll generate the calltree file and can be opened with kcachegrind.

```
$ python pyprof2calltree.py -i simple.prof -o simple.ct
writing converted data to: simple.ct

```
[0] http://pastebin.com/MCGntvU3

**Comment by pwaller** [comment]
Thanks again and sorry for the delay. If you don't hear from me within a week please do ping. 

When I run kcachegrind on simple.ct, I seem to have an empty profile. A) Is that what you expect? B) is there a bug here? C) How are you viewing the profiles?

Here's a screenshot of the resulting profile with the python profile module:

screenshot from 2017-01-06 08-09-22

Here is what I expect, and what you get with `pyprof2calltree -k -r simple.py`:

screenshot from 2017-01-06 08-09-53

**Comment by danalsan** [comment]
> When I run kcachegrind on simple.ct, I seem to have an empty profile.  A) Is that what you expect? B) is there a bug here?

I assume you're generating simple.ct with the version from my fork? 
Also, please make sure that you're processing a "profile" file. For that you need to generate it this way (and not with the -r option of pyprof2calltree):
`python -m profile -o simple.prof simple.py`

>  C) How are you viewing the profiles?
Once you have the profile file as before, I convert it (with my fork version) to a calltree file:
```
$ python pyprof2calltree.py -i simple.prof -o simple.ct
writing converted data to: simple.ct
```

And then I simply run kcachegrind on simple.ct
captura de pantalla de 2017-01-06 13-29-15

If you follow the above steps, you'll find that it won't work with your current master version. That is because of the Python profile format which is not currently supported.

Thanks!
Daniel

**Comment by pwaller** [comment]
Yes, I used your fork. Yes, I used `-m profile`. The screenshot above is the result, so something strange is going on. I attach the files involved for you to take a look.

[simple.zip](https://github.com/pwaller/pyprof2calltree/files/690021/simple.zip)

In case it is relevant, I generated the profile with `-m profile` under python2 and the kcachegrind log with pyprof2calltree running under python3.

```
$ python -V
Python 2.7.11+
$ python3 -V
Python 3.5.1+
```

**Comment by danalsan** [comment]
```
[dani@host]$ unzip simple.zip
Archive:  simple.zip
  inflating: simple.ct               
  inflating: simple.prof             
  inflating: simple.py               
  inflating: simple.py.log    
[dani@host]$ git clone https://github.com/danalsan/pyprof2calltree.git
Cloning into 'pyprof2calltree'...
remote: Counting objects: 200, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 200 (delta 0), reused 0 (delta 0), pack-reused 195
Receiving objects: 100% (200/200), 45.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (103/103), done.
Checking connectivity... done.
[dani@host]$ python -V
Python 2.7.12
[dani@host]$ python -m profile -o simple.prof_dani simple.py
[dani@host]$ python pyprof2calltree/pyprof2calltree.py -i simple.prof_dani -o simple.ct
writing converted data to: simple.ct
[dani@host]$ ls -al simple.ct
-rw-rw-r--. 1 dani dani 804 ene  6 15:21 simple.ct
```
However it's true that our profile files differ although they are same size:
```
[dani@host]$ ls -al simple.prof*
-rw-rw-r--. 1 dani dani 2921 Jan  6 08:06 simple.prof
-rw-rw-r--. 1 dani dani 2921 Jan  6 15:25 simple.prof_dani
[dani@host]$ diff simple.prof simple.prof_dani 
Binary files simple.prof and simple.prof_dani differ
[dani@host]$ cmp -l simple.prof simple.prof_dani  | wc -l
703
```
I don't know why our profile files differ.
```
[dani@host]$ python  
Python 2.7.12 (default, Sep 29 2016, 12:52:02) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import profile
>>> profile.__file__
'/usr/lib64/python2.7/profile.pyc'
```
I'm attaching simple.ct which I can visualize without issues with kcachegrind
[simple_ct.zip](https://github.com/pwaller/pyprof2calltree/files/690095/simple_ct.zip)

**Comment by pwaller** [comment]
So for some reason our two .ct files differ:

<details>

```diff
--- simple-yours.ct	2017-01-06 15:21:26.000000000 +0000
+++ simple-mine.ct	2017-01-06 08:06:14.829242552 +0000
@@ -1,75 +1,75 @@
 event: ns : Nanoseconds
 events: ns
-summary: 279999
+summary: 0
 fl=
 fn=setprofile
-0 126000
+0 0
 
 fl=
 fn=sleep
-0 54000
+0 0
 
 fl=profile
-fn=<code object <module> at 0x7f261fff33b0, file "simple.py", line 1>
-0 41999
+fn=<code object <module> at 0x7f5a7ad6c1b0, file "simple.py", line 1>
+0 0
 cfl=
 cfn=setprofile
 calls=1 0
-0 126000
+0 0
 cfl=simple.py
 cfn=<module>
 calls=1 1
-0 112000
+0 0
 
 fl=profile
 fn=profiler
 0 0
 cfl=profile
-cfn=<code object <module> at 0x7f261fff33b0, file "simple.py", line 1>
+cfn=<code object <module> at 0x7f5a7ad6c1b0, file "simple.py", line 1>
 calls=1 0
-0 279999
+0 0
 
 fl=simple.py
 fn=<module>
-1 11999
+1 0
 cfl=simple.py
 cfn=main
 calls=1 14
-1 100000
+1 0
 
 fl=simple.py
 fn=fun1
-3 5999
+3 0
 cfl=simple.py
 cfn=fun2
 calls=1 6
-3 44500
+3 0
 
 fl=simple.py
 fn=fun2
-6 15000
+6 0
 cfl=simple.py
 cfn=fun3
 calls=1 10
-6 81000
+6 0
 
 fl=simple.py
 fn=fun3
-10 20000
+10 0
 cfl=
 cfn=sleep
 calls=1 0
-10 54000
+10 0
 cfl=simple.py
 cfn=fun2
 calls=1 6
-10 44500
+10 0
 
 fl=simple.py
 fn=main
-14 4999
+14 0
 cfl=simple.py
 cfn=fun1
 calls=1 3
-14 95000
+14 0
```

</details>


I would like to get to the bottom of this before merging if possible.

Can you send your simple.prof and/or try doing a binary diff to understand why our two profiles are different?

If you take my .prof and generate a ct, is it empty? We should try and understand which thing is going wrong here.

**Comment by pwaller** [comment]
Ping :)

**Comment by pwaller** [comment]
Ping, again.

**Comment by pwaller** [comment]
I did just have another go at this, but I had no luck. I still get a profile with zero counts, even running all under python2.

In addition, if I try running it all under python3, I get the following stack trace:

```
writing converted data to: simple-3.out
Traceback (most recent call last):
  File "/home/pwaller/.local/bin/pyprof2calltree", line 11, in <module>
    load_entry_point('pyprof2calltree', 'console_scripts', 'pyprof2calltree')()
  File "/home/pwaller/Projects/pyprof2calltree/pyprof2calltree.py", line 356, in main
    kg.output(open(outfile, 'w'))
  File "/home/pwaller/Projects/pyprof2calltree/pyprof2calltree.py", line 213, in output
    for entry in sorted(self.entries, key=_entry_sort_key):
TypeError: unorderable types: str() < code()
```

**Comment by pwaller** [comment]
Hi There! Thanks again for the contribution, but as I haven't heard from you in a while I'm going to close this. We can reopen it and have another attempt if you get another chance to work on it. All the best!

**Pull request closed without merging**
