### PR TITLE
Support other time units besides nanoseconds

### PR DESCRIPTION
**Pull request by staticf0x**
So this is my PR for #57. Please take a look, I tried to make it as simple as possible and it's backwards compatible.

### CODE REVIEW

**Comment by meesha7** [comment]
Any chance of getting this reviewed/merged?

**Comment by pwaller** [comment]
Apologies for the delay. Life has been chaotic and this only gets what little spare time I have. It may seem a stupid question, but please can you provide short, clear instructions for testing that this behaves as you intend? I will follow those instructions and if we end up with the expected result, I am likely to merge this without much fuss. Please also feel free to ping this (repeatedly) on a timescale of ~1 per week if you don't hear from me. If I don't respond I am indisposed but I will get to this.

**Comment by meesha7** [comment]
Thanks for your reply! Good point about the example usage, here we go:

Take some test file like `test_prof.py`:
```py
from time import sleep

for _ in range(100):
    sleep(0.01)
```

Get the cProfile data: `python3 -m cProfile -s time -o test.prof test_prof.py`

Now use `pyprof2calltree` for different time units:

```sh
pyprof2calltree.py -i test.prof -o cachegrind.out.test.ns  # This is the default unit before this PR
pyprof2calltree.py -i test.prof -o cachegrind.out.test.us -s us
pyprof2calltree.py -i test.prof -o cachegrind.out.test.ms -s ms
pyprof2calltree.py -i test.prof -o cachegrind.out.test.s -s s
```

Now if you look at those file (in KCacheGrind) or just grepping:

```sh
cat cachegrind.out.test.ms | grep event
```

It should show:

```
event: ms : Milliseconds
events: ms
```

And of course all measured units should be scaled:

```sh
cat cachegrind.out.test.ms | grep -A 2 time.sleep
```

Would produce something like:

```
cfn=<built-in method time.sleep>
calls=100 0
1 1021
--
fn=<built-in method time.sleep>
0 1021
```

1021 ms, then 1021888 us etc for my file.

Thanks a lot! :)

**Comment by pwaller** [comment]
Ready to merge. If you feel like it, please also add yourself in [`CONTRIBUTORS.md`](https://github.com/pwaller/pyprof2calltree/blob/a8b9d9672f6f01170af51f17a2571624ffe8273a/CONTRIBUTORS.txt#L50-L51) and I'll hit merge.

**Comment by meesha7** [comment]
Ok done :)

**Pull request merged**
