### PR TITLE
Name de-duplication, change units, and add some tests

### PR DESCRIPTION
**Pull request by zbenjamin**
Major changes:
* Support multiple functions with the same name defined in the same file (such as inherited methods or inner functions)
* Change units from ticks (milliseconds) to nanoseconds. This fixes potentially large inaccuracy in time percentage calculations
* Add minimal tests

Minor changes:
* Add `__repr__` methods for easier debugging
* Fix creating callgraph profiles directly from cProfile entries
* Fix reccallcount for subentries
* Misc cleanups

### CODE REVIEW

**Comment by pwaller** [comment]
Thanks! I'm a little busy at the moment. I hope to be able to get to this soon. If you don't hear from me in 1 week please ping me. Apologies for the delay!

**Comment by zbenjamin** [comment]
ping!

**Comment by zbenjamin** [comment]
Ping on this again!

**Comment by pwaller** [comment]
Hi @zbenjamin! Thanks for the pull request and pinging me. Sorry I couldn't respond sooner, the first ping caught me when I was on holiday. I've now reviewed, tested and run the code as of 3196abb. I'm happy to merge as is. Could you please write a brief body to your pull request - just stating what has changed and why. Then I'll merge it rapidly and make a new release.

**Comment by pwaller** [comment]
Ping :) (will do a hyper-exponential backoff here and ping in the distant future).

**Comment by immerrr** [comment]
I tried this PR this morning and it untangled the call graph quite well. I still had some display issues with kcachegrind in Ubuntu 12.04, so I dug a bit into formats.

One thing is that the event definition is a bit incorrect, according to [callgrind format description](http://valgrind.org/docs/manual/cl-format.html#cl-format.overview.misc), the header should look like
```
event: ns : Nanoseconds
events: ns
```

Also, it is unnecessary to deduplicate using `funcname:LN` format as callgrind supports [name compression](`http://valgrind.org/docs/manual/cl-format.html#cl-format.overview.compression1`) in `(1) funcname` format and allows to reference that funcname with only `(1)` later on. The only drawback of such approach is the decreased readability of `fn=(1)` references in raw output file.

**Comment by pwaller** [comment]
Ping @zbenjamin again

**Comment by pwaller** [comment]
Ping @zbenjamin please could you respond to @immerrr and write a PR body?

Sorry for not pinging more frequently.

**Comment by immerrr** [comment]
I might try to have a look at it over the weekend.

**Comment by zbenjamin** [comment]
@pwaller I just added a summary of the changes to the PR body. More detail is available in the commits themselves. Sorry that took so long

**Comment by zbenjamin** [comment]
Ping @pwaller

**Comment by immerrr** [comment]
@zbenjamin what do you think about my notes from [here](https://github.com/pwaller/pyprof2calltree/pull/15#issuecomment-161954083)?

**Comment by zbenjamin** [comment]
@immerrr Thanks for the format fix!

I think perhaps you're misunderstanding the problem that the name de-duplication code solves. Suppose you have Python file that looks like this:
`import cProfile
import pstats
from pyprof2calltree import CalltreeConverter

def top():
    C1.func()
    C2.func()

class C1(object):
    @staticmethod
    def func():
        pass

class C2(object):
    @staticmethod
    def func():
        pass

profile = cProfile.Profile()
profile.enable()
top()
profile.disable()
stats = pstats.Stats(profile)
converter = CalltreeConverter(stats)
with open("foo.callgrind", "w") as f:
    converter.output(f)
`

Running this on master results in the following file:
`events: Ticks
summary: 0
fn=<method 'disable' of '_lsprof.Profiler' objects>
0 0

fl=foo.py
fn=top
5 0
cfl=foo.py
cfn=func
calls=1 10
5 0
cfl=foo.py
cfn=func
calls=1 15
5 0

fl=foo.py
fn=func
10 0

fl=foo.py
fn=func
15 0
`

If you open that up in kcachegrind, you can see that kcachegrind interprets that as `top` calling a single function called `func` which happens to have 2 cost lines (one on line 10 and one on line 15). The problem is that the callgrind format is designed for C-like languages where a name is only used once in a single compilation unit and thus the <filename, function name> pair uniquely identifies a function. This is not the case in Python. Unless I'm misunderstanding something, name compression can't help here and the only way to disambiguate the two functions is to change their names.

**Comment by immerrr** [comment]
I was  pointing out that there already exists support for function name disambiguation in cachegrind format, you don't need to work it around adding `:LINENO` suffix to function names.  Your example could be fixed by making the first function `(1) func`, the second function `(2) func` and referring to them later on as `(1)` and `(2)` respectively. You still need to disambiguate the functions in the conversion routine, though.

I guess the word "compression" is a bit of a misnomer here. Referring to functions by their numbers rather than names is incidentally usually shorter, probably that's why it is called like that. Still, the technique is perfectly capable of disambiguating the names on the way, too.

**Comment by immerrr** [comment]
At least that's what I thought back in the day. I can't seem to find any working snippets for this now.

**Comment by immerrr** [comment]
As of now, qcachegrind merges the nodes in the callgraph if they have the same names, so apparently I was wrong.

**Comment by pwaller** [comment]
Thanks for the contribution and sorry it took a while to get it in, you caught me on holiday :)

**Comment by pwaller** [comment]
I've cut https://pypi.python.org/pypi/pyprof2calltree/1.4.0 and [added you to the contributors](https://github.com/pwaller/pyprof2calltree/blob/master/CONTRIBUTORS.txt). Thanks again!

@immerrr if you would like to be listed in the contributors too for testing and pull request feedback, please submit a PR to edit the file.

**Comment by zbenjamin** [comment]
Thanks!

**Pull request merged**
